name: "benchmark"
channels:
  - nvidia
  - nvidia/label/cuda-12.5.1
  - conda-forge
dependencies:
  - python=3.10.*
  - pip
  - git
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.3.1
    - torchvision
    - tensorflow==2.16.1
    - tensorflow_graphics
    - nvidia-dali-cuda120
    - trimesh==4.4.0
    - numpy==1.26.4
    - tqdm
    - scipy
    - h5py
    - zarr
    - pyyaml
    - psutil
    - opencv-python-headless
    - matplotlib
    - git+https://github.com/Jan-Hoc/PySysLoadBench.git@v0.1.3
    - poetry
    - python-dotenv
    - ruff