name: Build Standard Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: build and push image to dockerhub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USER}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          env:
            username: ${{secrets.DOCKERHUB_USER}}
            imagename: dsi-bench
            tag: latest
          run: |
            ls -la 
            docker build --build-arg version=standard --build-arg build=0 . -f Dockerfile -t $username/$imagename:$tag
        - name: push the docker image
          id: push-docker-image
          env:
            username: ${{secrets.DOCKERHUB_USER}}
            imagename: dsi-bench
            tag: latest
          run: docker push $username/$imagename:$tag